version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    restart: always # define the policy of restart in case the server went down
    build: ./Node_app_image
    ports:
      - '4001:8081'
