apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: cygnetops/multi-server-pgfix-5-11
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379' # redis default port (must be between quotes as string)
            - name: PGUSER
              value: postgres # by default PGUSER
            - name: PGHOST
              value: postgres-cluster-ip-service # ClusterIP of postgres pod
            - name: PGPORT 
              value: '5432' # postgres default port (must be between quotes as string)
            - name: PGDATABASE 
              value: postgres  # default postgres database 
            - name: PGPASSWORD # name of the variable 
              valueFrom:
                secretKeyRef:
                  name: pgpassword # the secret name created
                  key: PGPASSWORD # the secret key created
